[book]
authors = ["Julian Hofer"]
language = "zh_cn"
multilingual = false
src = "src"
title = "基于 Rust 和 GTK 4 的 GUI 开发"


[output.html]
default-theme = "Rust"
git-repository-url = "https://github.com/Mario-Hero/GTK-Rust-Book-zh_cn"
git-repository-icon = "fa-github"
additional-css = ["theme/style.css"]
playground.runnable = false
